import type { Metadata } from "next";
import { Nobile } from "next/font/google";
import "./globals.css";

const nobile = Nobile({
  variable: "--font-nobile",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nobile.variable} antialiased`}>{children}</body>
    </html>
  );
}
